
-- T@ENTITYNAME@S DEFINITION

-- DROP TABLE

-- DROP TABLE T@ENTITYNAME@S;

CREATE TABLE T@ENTITYNAME@S (
	_ID SERIAL4 NOT NULL,
    @ATTRMODEL@
    USERID INT4 NOT NULL,
    CREATEDAT DATE NOT NULL,
	UPDATEDAT DATE NULL,
    CONSTRAINT T@ENTITYNAME@_PKEY PRIMARY KEY (_ID),
    @CONSTRAINTS@
);

COMMENT ON TABLE T@ENTITYNAME@S IS '@Description@';

@ALTERTABLE@

@CREATETABLE@