
-- T@ENTITYNAME@ DEFINITION

-- DROP TABLE

-- DROP TABLE T@ENTITYNAME@;

CREATE TABLE T@ENTITYNAME@ (
	_ID SERIAL4 NOT NULL,
    @ATTRMODEL@
    USERID INT4 NOT NULL,
    CREATEDAT DATE NOT NULL,
	UPDATEDAT DATE NULL,
    CONSTRAINT T@ENTITYNAME@_PKEY PRIMARY KEY (_ID),
    @CONSTRAINTS@
);

COMMENT ON TABLE T@ENTITYNAME@ IS '@Description@';

ALTER TABLE T@ENTITYNAME@ ADD CONSTRAINT T@ENTITYNAME@_USERID_FK FOREIGN KEY(USERID) REFERENCES TUSERS(_ID);
@ALTERTABLE@

@CREATETABLE@