-- Auto Generated 
-- @author Andres Felipe Escobar López
-- @date 2024
-- @copyright Tecnologico de Antioquia 2024

-- TUSERS DEFINITION

-- DROP TABLE

-- DROP TABLE TUSERS;

CREATE TABLE TUSERS (
	_ID SERIAL4 NOT NULL,
	USERNAME VARCHAR(150) NOT NULL,
	BIO VARCHAR(500) NULL,
	AVATAR VARCHAR(250) NULL,
	EMAIL VARCHAR(250) NOT NULL,
	PASSWORD VARCHAR(250) NOT NULL,
    CREATEDAT DATE NOT NULL,
	UPDATEDAT DATE NULL,
	CONSTRAINT TUSER_PKEY PRIMARY KEY (_ID),
	CONSTRAINT TUSER_USERNAME_KEY UNIQUE (USERNAME),
	CONSTRAINT TUSER_EMAIL_KEY UNIQUE (EMAIL)
);

COMMENT ON TABLE TUSERS IS 'USER MANAGEMENT.';


@CREATETABLE@